name: MultiChatBridge
version: 1.4.1
author: Revilo410
main: com.olivermartin410.plugins.SpigotComm
softdepend: [Vault]
commands:
   nick:
      description: Gives a player a nickname
      usage: /nick <player> <nickname / off>
      permission: multichatbridge.nick
      permission-message: You do not have permission (multichatbridge.nick)